"""Six skills carry the style block, and all six carry the SAME bytes.

`skills/` is pruned from the sdist and the wheel packages only `xcheck`, so a skill cannot
read the style out of Python at run time — the bytes have to be literally in each file.
Six copies is therefore forced, and this module is what makes six copies safe: an equality
check against the one source, plus three counterfactuals that have been watched to fail.

A block that is NEARLY the same in six files is worse than one block, because the
differences are invisible and each is a place a guarantee quietly weakened.
"""

import pathlib
import shutil
import subprocess
import sys
import tempfile
import unittest

sys.path.insert(0, str(pathlib.Path(__file__).resolve().parent.parent))

from tests import test_launch_surfaces as ls

REPO = pathlib.Path(__file__).resolve().parent.parent
RENDERER = REPO / "ci" / "render-style.py"
BEGIN = "<!-- xcheck:style:begin -->"
END = "<!-- xcheck:style:end -->"

# The real OpenCode transform, from `launchers/install-launchers.sh`. Everything above the
# SECOND `---` is dropped, so a directive in frontmatter reaches nobody.
STRIPPER = ["awk", "c==2{print} /^---$/{c++; next}"]


def source_body():
    src = (REPO / "styles" / "eli5.md").read_text()
    b = src.index(BEGIN) + len(BEGIN)
    return src[b:src.index(END, b)].strip("\n")


def carried_body(text):
    """The bytes a skill actually carries between its markers, or None."""
    if BEGIN not in text or END not in text:
        return None
    b = text.index(BEGIN) + len(BEGIN)
    return text[b:text.index(END, b)].strip("\n")


def skills(root=REPO):
    return sorted((root / "skills").glob("*/SKILL.md"))


def strip_frontmatter(text):
    """Run the REAL awk pipeline. Not a Python reimplementation of it: the thing under
    test is the transform that ships, and a second implementation is a second thing to
    drift."""
    p = subprocess.run(STRIPPER, input=text, capture_output=True, text=True)
    assert p.returncode == 0, p.stderr
    return p.stdout


class AllSixCarryTheSameBytes(unittest.TestCase):
    """Criteria 1, 6, 7 — identity, coverage, and nothing lost to make room."""

    def test_every_skill_carries_the_block_byte_for_byte(self):
        body = source_body()
        files = skills()
        self.assertEqual(6, len(files), f"expected six launcher skills, found {len(files)}")
        print(f"\nSTYLE COVERAGE: {len(files)} skill(s), block {len(body.encode())} bytes")
        wrong = []
        for f in files:
            text = f.read_text()
            self.assertEqual(1, text.count(BEGIN), f"{f}: begin marker count")
            self.assertEqual(1, text.count(END), f"{f}: end marker count")
            got = carried_body(text)
            print(f"  {f.parent.name:20} {len(got.encode()):5} bytes  "
                  f"{'identical' if got == body else 'DIFFERS'}")
            if got != body:
                wrong.append(f.parent.name)
                import difflib
                sys.stdout.writelines(difflib.unified_diff(
                    got.splitlines(keepends=True), body.splitlines(keepends=True),
                    fromfile=f"{f.parent.name} (carried)", tofile="styles/eli5.md (source)"))
        self.assertEqual([], wrong, f"skills carrying a drifted block: {wrong}")

    def test_the_render_is_reproducible_so_the_repository_is_current(self):
        p = subprocess.run([sys.executable, str(RENDERER), "--check"],
                           capture_output=True, text=True, cwd=str(REPO))
        print(f"  render-style.py --check on the repository: rc={p.returncode}")
        self.assertEqual(0, p.returncode, p.stdout + p.stderr)


class TheBlockSurvivesTheFrontmatterStripper(unittest.TestCase):
    """Criterion 2, and its counterfactual C.

    OpenCode commands are generated by dropping everything above the second `---`. A
    directive placed in frontmatter is a directive nobody receives — this repository has
    shipped that defect before.
    """

    def test_the_block_is_in_what_survives_for_every_skill(self):
        body = source_body()
        for f in skills():
            survived = strip_frontmatter(f.read_text())
            self.assertIn(BEGIN, survived,
                          f"{f.parent.name}: the block did not survive the stripper — it "
                          f"is in the frontmatter, where it reaches nobody")
            self.assertEqual(body, carried_body(survived),
                             f"{f.parent.name}: the block survived but not intact")
        print(f"\n  stripper: the block survives in {len(skills())}/6 skill(s), intact")

    def test_counterfactual_c_a_block_in_frontmatter_does_not_survive(self):
        """The plant and its control, in one method. Without the control arm, a broken
        harness would make the plant look caught."""
        f = skills()[0]
        original = f.read_text()

        control = strip_frontmatter(original)
        self.assertIn(BEGIN, control, "CONTROL FAILED: the block is in the body and "
                                      "still did not survive — the harness is broken, "
                                      "so the plant below would prove nothing")

        without = original.replace(f"{BEGIN}\n{carried_body(original)}\n{END}\n\n", "")
        lines = without.splitlines(keepends=True)
        close = next(i for i, ln in enumerate(lines) if i and ln.strip() == "---")
        planted = ("".join(lines[:close]) + BEGIN + "\n" + source_body() + "\n" + END
                   + "\n" + "".join(lines[close:]))
        self.assertIn(BEGIN, planted, "the plant did not plant anything")

        survived = strip_frontmatter(planted)
        print(f"  counterfactual C — block moved into {f.parent.name}'s frontmatter: "
              f"present before the stripper={BEGIN in planted}, "
              f"after={BEGIN in survived}")
        self.assertNotIn(BEGIN, survived,
                         "a block in frontmatter reached the far side of the stripper — "
                         "either the stripper changed or the plant missed")


class TheGateBites(unittest.TestCase):
    """Counterfactuals A and B, against a temp copy of the tree.

    A gate nobody has watched fail is a gate nobody knows the shape of.
    """

    def setUp(self):
        self.tmp = pathlib.Path(tempfile.mkdtemp(prefix="xcheck-human-style-"))
        self.addCleanup(shutil.rmtree, self.tmp, ignore_errors=True)
        shutil.copytree(REPO / "styles", self.tmp / "styles")
        shutil.copytree(REPO / "skills", self.tmp / "skills")

    def check(self):
        return subprocess.run([sys.executable, str(RENDERER), "--check",
                               "--root", str(self.tmp)], capture_output=True, text=True)

    def test_counterfactual_a_a_deleted_block_reddens_the_gate_and_is_named(self):
        clean = self.check()
        self.assertEqual(0, clean.returncode,
                         f"CONTROL FAILED: the copied tree was already dirty\n{clean.stdout}")

        victim = skills(self.tmp)[2]
        text = victim.read_text()
        victim.write_text(text.replace(f"{BEGIN}\n{carried_body(text)}\n{END}\n\n", ""))

        red = self.check()
        print(f"\n  counterfactual A — block deleted from {victim.parent.name}: "
              f"control rc={clean.returncode}, planted rc={red.returncode}")
        print(f"    {[ln for ln in red.stdout.splitlines() if ln.startswith('DRIFT')]}")
        self.assertEqual(1, red.returncode, "a deleted block did not redden the gate")
        self.assertIn(victim.parent.name, red.stdout,
                      "the failure did not name the skill that lost its block")
        self.assertIn("DRIFT in 1", red.stdout)

    def test_counterfactual_b_one_changed_byte_reddens_the_gate_and_shows_in_the_diff(self):
        """The arm that separates an identity check from a substring check. A gate that
        only asks 'is the block present' passes on a block whose meaning was inverted."""
        self.assertEqual(0, self.check().returncode, "CONTROL FAILED: tree already dirty")

        victim = skills(self.tmp)[4]
        text = victim.read_text()
        at = text.index("normal mode")
        victim.write_text(text[:at] + "normol mode" + text[at + len("normal mode"):])

        red = self.check()
        # Both sides of the hunk. Matching on the ORIGINAL spelling would print only the
        # `+` line, since the mutated line no longer contains it — and half a diff is not
        # evidence that the diff shows the byte.
        shown = [ln.rstrip() for ln in red.stdout.splitlines()
                 if ln[:1] in "+-" and ("normal mode" in ln or "normol mode" in ln)]
        print(f"  counterfactual B — one byte changed in {victim.parent.name}: "
              f"rc={red.returncode}")
        for ln in shown:
            print(f"    {ln}")
        self.assertEqual(1, red.returncode,
                         "one changed byte inside the block did not redden the gate, so "
                         "this is a substring check wearing an identity check's name")
        self.assertTrue(shown, "the diff did not show the changed byte")
        self.assertIn(victim.parent.name, red.stdout)


class TheBlockIsCleanWhereItActuallySits(unittest.TestCase):
    """Criterion 8 — re-probed IN SITU, not only as a bare body.

    `scan_claims` reports the innermost NON-EMPTY heading frame, so identical bytes can
    scan clean standalone and dirty inside a document whose frames differ. Phase 1 probed
    the body; this probes the file an agent is actually handed.
    """

    def test_the_block_contributes_no_claim_in_any_finished_skill(self):
        from_block, per_file = 0, {}
        for f in skills():
            text = f.read_text()
            lines = text.splitlines()
            lo = next(i for i, l in enumerate(lines, 1) if BEGIN in l)
            hi = next(i for i, l in enumerate(lines, 1) if END in l)
            claims = ls.scan_claims(text)
            inside = [c for c in claims if lo <= c[0] <= hi]
            from_block += len(inside)
            per_file[f.parent.name] = (len(claims), len(inside),
                                       sorted({tuple(sc) for _, sc, _ in claims}))
            for n, scope, s in inside:
                print(f"    {f.parent.name}:{n} scope={scope or '[UNSCOPED]'}: {s}")
        print("\n  IN-SITU CLAIM PROBE (test_launch_surfaces.scan_claims)")
        for name, (tot, mine, scopes) in per_file.items():
            print(f"    {name:20} file={tot:2}  from block={mine}  scopes={scopes}")
        self.assertEqual(0, from_block,
                         "the block makes a containment claim once it is inside a skill")

    def test_inserting_the_block_did_not_rescope_the_claims_below_it(self):
        """The block opens a `##` frame in the middle of each file. A naive innermost-wins
        rule would hand every claim below it an empty scope; `scan_claims` falls through to
        the innermost NON-EMPTY frame instead. Asserted, because a silent re-scoping would
        turn correctly-scoped guarantees into unscoped ones without changing a word."""
        unscoped = []
        total = 0
        for f in skills():
            for n, scope, s in ls.scan_claims(f.read_text()):
                total += 1
                if not scope:
                    unscoped.append(f"{f.parent.name}:{n}: {s[:80]}")
        print(f"  claims across the six skills: {total}, unscoped: {len(unscoped)}")
        self.assertEqual([], unscoped,
                         "a claim lost its launch-mode scope when the block was inserted")
        # 20 -> 22 on 2026-09-03 (phase 15). The block still contributes none: the two
        # new claims are both in `xcheck-status`, whose exemption line says it is
        # read-only and whose disclosure now names the two controls that would still
        # have mattered. The other five skills had their disclosure REWRITTEN, not
        # extended, and their counts are byte-for-byte what they were. Unscoped stayed
        # at 0, which is the invariant this test actually holds.
        # 22 -> 28 on 2026-09-03 (phase 4 of the third-audit response). The five writing
        # launchers became wrappers, and the canonical wrapper block NAMES the eight
        # controls the dispatched session runs under, where the old disclosure spent its
        # sentences saying those same eight were absent: plan 3 -> 5, audit 4 -> 5,
        # remediate 4 -> 6, verify 3 -> 5, triage 3 -> 2 (it lost the lock-discipline
        # block with the rest of the role instructions). `xcheck-status` is untouched at
        # 5. The style block still contributes none, and unscoped stayed at 0 — the
        # invariant this test actually holds.
        self.assertEqual(28, total,
                         "the claim count over the six skills moved; it was 28 after "
                         "phase 4 and the style block contributes none")


if __name__ == "__main__":
    unittest.main(verbosity=2)
