"""A derived knowledge layer, and the six things it must never become.

The audit called this the P2 feature most likely to quietly become a competing truth, so
the module is mostly refusals and this suite is mostly about the boundary rather than the
analysis. The audit's diagram is the specification:

    state.json + events -> projection -> analysis -> proposal -> human review
                                                                      |
                                                          an existing write verb -> state

Every arrow is one-way. What is asserted here, in the order a shortcut would appear:

  1. the bundle is a PROJECTION — reproducible from state.json plus the event stream
     alone, and byte-identical when re-derived from the same two inputs;
  2. six record types, each with real content and full provenance;
  3. a CONFLICT IS KEPT — two records that disagree both survive, joined by
     `conflicts_with`, with no last-wins anywhere;
  4. six forbidden effects, refused SEPARATELY — and proved distinct, because six arms
     that collapse into one cover one rule;
  5. a proposal changes no byte of state.json;
  6. off by default, generated by an explicit verb, with no vector store or graph
     database anywhere in the dependency set.
"""

import ast
import collections
import hashlib
import json
import subprocess
import sys
import unittest
from pathlib import Path

from tests.harness import (needs_live_corpus, 
    REPO, Fixture, XCHECK, finding_record, queue_pass, state_doc, xcheck_submodule,
)

okf = xcheck_submodule("okf")
state_mod = xcheck_submodule("state")
util = xcheck_submodule("util")

# A state with enough shape to project all six types: findings across one dimension
# (three of them, so the hypothesis fires), a done pass, and the harness norm.
FINDINGS = [finding_record("F-0001", status="accepted", severity="critical"),
            finding_record("F-0002", status="reported", title="a second finding"),
            finding_record("F-0003", status="fixed", title="a third finding")]

# A human transition: `session_id` is absent, which is exactly what makes it a DECISION
# rather than something an agent did.
#
# PHASE 6 (fourth audit). These carried `id` and `at` — fields production has never
# emitted. Real `state_transition` events carry `target` and `ts`, so every decision
# record on the real stream read `None moved reported -> accepted` while this fixture
# read correctly, which is why the projection shipped broken. The fixture is the
# production shape now, and `TheProjectionReadsTheProductionSchema` checks it against the
# real stream rather than trusting it.
EVENTS = [{"event": "state_transition", "target": "F-0001", "from_status": "reported",
           "to_status": "accepted", "verb": "set-status", "ts": "2026-09-01"},
          {"event": "state_transition", "target": "F-0003", "session_id": "a" * 16,
           "from_status": "accepted", "to_status": "fixed", "verb": "record-fix"}]


def built():
    fx = Fixture(state_doc(findings=FINDINGS, queue=[queue_pass("P-01", done=True)]))
    st = state_mod.load_state(fx.audit)
    return fx, st, okf.project_bundle(st, EVENTS, today="2026-09-03")


class TheSixRecordTypes(unittest.TestCase):

    def test_each_type_is_produced_with_full_provenance(self):
        fx, _st, records = built()
        self.addCleanup(fx.cleanup)
        by_type = {}
        for r in records:
            by_type.setdefault(r["type"], []).append(r)
        self.assertEqual(sorted(okf.RECORD_TYPES), sorted(by_type),
                         "a declared record type was never produced")
        print("SIX RECORD TYPES")
        for kind in okf.RECORD_TYPES:
            example = by_type[kind][0]
            for field in okf.RECORD_FIELDS:
                self.assertIn(field, example, f"{kind} is missing {field}")
            print(f"  {kind:<12} {example['text'][:64]}")
            print(f"  {'':<12} rev={example['source_revision']} "
                  f"confidence={example['confidence']!r} scope={example['scope']!r} "
                  f"freshness={example['freshness']!r} locator={example['locator']!r}")

    def test_the_three_relations_exist_and_are_used(self):
        fx, _st, records = built()
        self.addCleanup(fx.cleanup)
        self.assertEqual((okf.DERIVED_FROM, okf.SUPERSEDES, okf.CONFLICTS_WITH),
                         okf.RELATIONS)
        used = {rel for r in records for rel in r["links"]}
        self.assertIn(okf.DERIVED_FROM, used)
        with self.assertRaises(ValueError):
            okf.okf_link(records[0], "implies", "x")


class AConflictIsKept(unittest.TestCase):
    """No last-wins anywhere. Two records that disagree about the same locator are two
    things someone said; picking a winner would be inventing a third."""

    def test_both_conflicting_records_survive_and_point_at_each_other(self):
        a = okf.knowledge_record(okf.CLAIM, "the lock is released on every path", 7,
                                 locator="xcheck/runner.py:100", finding="F-0009")
        b = okf.knowledge_record(okf.CLAIM, "the lock leaks on the timeout path", 7,
                                 locator="xcheck/runner.py:100", finding="F-0009")
        records = [a, b]
        pairs = okf.conflicts(records)
        self.assertEqual(1, len(pairs))
        self.assertEqual(2, len(records), "a record was dropped to resolve the conflict")
        self.assertIn(b["id"], a["links"][okf.CONFLICTS_WITH])
        self.assertIn(a["id"], b["links"][okf.CONFLICTS_WITH])
        print("KEPT CONFLICT — both survive, neither wins")
        print(f"  {a['id']}  {a['text']}")
        print(f"  {b['id']}  {b['text']}")
        print(f"  joined by `{okf.CONFLICTS_WITH}` in both directions; "
              f"{len(records)} records in, {len(records)} out")

    def test_the_module_contains_no_resolution_step(self):
        """Structural, not a spot check: nothing in the module names a winner."""
        text = Path(xcheck_submodule("okf").__file__).read_text(encoding="utf-8")
        body = "\n".join(l for l in text.splitlines()
                         if not l.strip().startswith("#") and "resolution" not in l
                         and "resolving" not in l and "resolve" not in l)
        for banned in ("last-wins", "lastwins", ".pop(", "del "):
            self.assertNotIn(banned, body, f"{banned} appears in a module that must keep "
                                           f"every conflicting record")


class TheBackChannelIsProposalOnly(unittest.TestCase):

    def test_all_six_forbidden_effects_are_refused(self):
        self.assertEqual(
            {"open-finding", "close-finding", "move-status", "weaken-policy",
             "replace-evidence", "raise-own-confidence"}, set(okf.FORBIDDEN))
        print("SIX REFUSALS")
        for effect in okf.FORBIDDEN:
            with self.assertRaises(PermissionError) as caught:
                okf.apply_effect(effect, "F-0001")
            msg = str(caught.exception)
            self.assertIn(okf.FORBIDDEN[effect][0], msg)
            print(f"  {effect:<22} {msg[:118]}")

    def test_the_six_refusals_are_distinct(self):
        """The control. Six arms that collapse into one cover one rule, so the messages
        are compared to each other and not only to a substring of themselves."""
        messages = {e: okf.refuse(e) for e in okf.FORBIDDEN}
        self.assertEqual(len(okf.FORBIDDEN), len(set(messages.values())),
                         "two forbidden effects produce the same refusal")
        # Stronger than distinctness: each message must name ITS OWN effect and no other
        # effect's distinguishing words, or six near-identical sentences would pass.
        for effect, msg in messages.items():
            for other, (what, _why) in okf.FORBIDDEN.items():
                if other != effect:
                    self.assertNotIn(what, msg,
                                     f"the {effect} refusal also describes {other}")
        with self.assertRaises(ValueError):
            okf.refuse("delete-the-repository")
        print(f"DISTINCT    {len(messages)} refusals, {len(set(messages.values()))} "
              f"unique, and none names another's effect")

    def test_a_proposal_holds_no_capability_and_names_an_existing_verb(self):
        fx, _st, records = built()
        self.addCleanup(fx.cleanup)
        p = okf.okf_proposal("accept", "F-0002",
                             "three findings share this dimension", records[:2],
                             verb="xcheck set-status F-0002 accepted")
        self.assertEqual("proposed", p["status"])
        self.assertIn("changes nothing", p["note"])
        self.assertNotIn("apply", p)
        print(f"PROPOSAL    verb={p['verb']!r} status={p['status']!r} "
              f"evidence={p['evidence']}")


class AProposalChangesNothing(unittest.TestCase):

    def test_generating_a_bundle_and_a_proposal_leaves_state_json_byte_identical(self):
        fx, st, records = built()
        self.addCleanup(fx.cleanup)
        path = Path(fx.audit) / "state.json"
        before = path.read_bytes()

        p = okf.okf_proposal("accept", "F-0002", "a proposal", records[:1],
                             verb="xcheck set-status F-0002 accepted")
        okf.write_bundle(fx.root, records, proposals=[p])
        after = path.read_bytes()
        self.assertEqual(before, after, "the bundle wrote to canonical state")
        self.assertEqual(st.state_revision,
                         state_mod.load_state(fx.audit).state_revision)
        print(f"UNCHANGED   state.json {len(before)} bytes before, {len(after)} after; "
              f"revision {st.state_revision} unmoved; "
              f"{sum(1 for _ in records)} records and 1 proposal written to audit/okf/")

    def test_the_only_path_to_state_is_an_existing_write_verb_run_by_a_human(self):
        """The proposal names a verb; running THAT verb is what moves state. The bundle
        has no other path, and the six refusals above are why."""
        fx, _st, records = built()
        self.addCleanup(fx.cleanup)
        path = Path(fx.audit) / "state.json"
        before = path.read_bytes()
        p = okf.okf_proposal("accept", "F-0002", "a proposal", records[:1],
                             verb="set-status F-0002 accepted")
        self.assertEqual(before, path.read_bytes())

        # A human runs the named verb. NOW state moves — through the same write path it
        # would have taken with no OKF in the picture.
        rc = subprocess.run([sys.executable, str(XCHECK), "--project", str(fx.root),
                             *p["verb"].split()], capture_output=True, text=True)
        self.assertEqual(0, rc.returncode, rc.stderr or rc.stdout)
        self.assertNotEqual(before, path.read_bytes())
        moved = state_mod.load_state(fx.audit)
        self.assertEqual("accepted",
                         next(r.status for r in moved.findings if r.id == "F-0002"))
        print(f"THE PATH    proposal -> human -> `xcheck {p['verb']}` -> F-0002 accepted "
              f"(revision now {moved.state_revision})")


class TheBundleIsDerived(unittest.TestCase):

    def test_the_projection_is_reproducible_from_state_and_events_alone(self):
        fx, st, first = built()
        self.addCleanup(fx.cleanup)
        again = okf.project_bundle(st, EVENTS, today="2026-09-03")
        self.assertEqual(json.dumps(first, sort_keys=True),
                         json.dumps(again, sort_keys=True))
        # And from a state loaded fresh off disk, which is the real claim: the only
        # inputs are the two files.
        reloaded = okf.project_bundle(state_mod.load_state(fx.audit), EVENTS,
                                      today="2026-09-03")
        self.assertEqual(json.dumps(first, sort_keys=True),
                         json.dumps(reloaded, sort_keys=True))
        print(f"REPRODUCIBLE {len(first)} records, byte-identical from a freshly loaded "
              f"state.json + events.jsonl")

    def test_the_manifest_checksums_every_file_and_catches_a_changed_byte(self):
        fx, _st, records = built()
        self.addCleanup(fx.cleanup)
        manifest = okf.write_bundle(fx.root, records)
        self.assertEqual([], okf.verify_bundle(fx.root))
        self.assertEqual(len(records), manifest["files"]["records.jsonl"]["rows"])

        rows = Path(okf.bundle_dir(fx.root), "records.jsonl")
        rows.write_text(rows.read_text(encoding="utf-8") + "{}\n", encoding="utf-8")
        problems = okf.verify_bundle(fx.root)
        self.assertEqual(["records.jsonl does not match its manifest checksum"], problems)
        print(f"MANIFEST    {problems[0]}")

    def test_no_vector_store_and_no_graph_database(self):
        """Read the module's AST, not its prose. The module's own docstring says "no
        vector store, no graph database, no embedding model", so a substring hunt over
        the source finds the words it is looking for in the sentence promising they are
        absent — the self-scanning-detector trap, in its purest form."""
        source = Path(xcheck_submodule("okf").__file__).read_text(encoding="utf-8")
        tree = ast.parse(source)
        imports = set()
        for node in ast.walk(tree):
            if isinstance(node, ast.Import):
                imports.update(a.name.split(".")[0] for a in node.names)
            elif isinstance(node, ast.ImportFrom) and node.module:
                imports.add(node.module.split(".")[0])
        self.assertEqual({"hashlib", "json", "datetime", "pathlib", "xcheck"},
                         imports, "the derived layer grew a dependency")

        # And no banned name appears as an identifier or a string VALUE — comments and
        # docstrings excluded, because those are where the promise is written.
        names = {n.id for n in ast.walk(tree) if isinstance(n, ast.Name)}
        names |= {n.attr for n in ast.walk(tree) if isinstance(n, ast.Attribute)}
        # Excluded by node IDENTITY, not by text: `ast.get_docstring` returns the
        # CLEANED docstring (dedented, stripped), which never equals the raw constant, so
        # subtracting the cleaned text removes nothing and the promise gets scanned.
        doc_nodes = set()
        for n in ast.walk(tree):
            if isinstance(n, (ast.Module, ast.FunctionDef, ast.ClassDef)):
                body = getattr(n, "body", None)
                if body and isinstance(body[0], ast.Expr) and \
                        isinstance(body[0].value, ast.Constant) and \
                        isinstance(body[0].value.value, str):
                    doc_nodes.add(id(body[0].value))
        strings = {n.value.lower() for n in ast.walk(tree)
                   if isinstance(n, ast.Constant) and isinstance(n.value, str)
                   and id(n) not in doc_nodes}
        for banned in ("faiss", "chroma", "neo4j", "networkx", "sqlite3", "embedding",
                       "vector"):
            self.assertNotIn(banned, {n.lower() for n in names}, banned)
            for text in strings:
                self.assertNotIn(banned, text, f"{banned} in a string value")
        print(f"DEPENDENCIES {sorted(imports)} — no vector store, no graph database, "
              f"asserted over the AST rather than over the prose that promises it")


class OffByDefaultAndExplicit(unittest.TestCase):

    def test_the_flag_is_off_and_the_verb_generates_nothing(self):
        self.assertEqual("off", util.CONF_DEFAULTS[okf.FLAG])
        self.assertIn(okf.FLAG, util.BOOLEAN_CONF)
        self.assertFalse(okf.okf_enabled({}))
        fx = Fixture(state_doc(findings=FINDINGS, queue=[queue_pass("P-01", done=True)]))
        self.addCleanup(fx.cleanup)
        rc = subprocess.run([sys.executable, str(XCHECK), "--project", str(fx.root), "okf"],
                            capture_output=True, text=True)
        self.assertEqual(0, rc.returncode, rc.stderr)
        self.assertIn("okf: off", rc.stdout)
        self.assertFalse(okf.bundle_dir(fx.root).exists(),
                         "the bundle was generated with the flag off")
        print(f"OFF         {rc.stdout.splitlines()[0]}  (no audit/okf/ directory)")

    def test_generating_it_is_an_explicit_verb_and_never_a_step_in_a_run(self):
        fx = Fixture(state_doc(findings=FINDINGS, queue=[queue_pass("P-01", done=True)]))
        self.addCleanup(fx.cleanup)
        conf = Path(fx.audit) / "orchestrator.conf"
        existing = conf.read_text(encoding="utf-8") if conf.exists() else ""
        conf.write_text(existing + f"\n{okf.FLAG}=on\n", encoding="utf-8")
        rc = subprocess.run([sys.executable, str(XCHECK), "--project", str(fx.root), "okf"],
                            capture_output=True, text=True)
        self.assertEqual(0, rc.returncode, rc.stderr or rc.stdout)
        self.assertTrue(okf.bundle_dir(fx.root).exists())
        self.assertIn("conflicts KEPT", rc.stdout)
        self.assertIn("DERIVED", rc.stdout)
        for line in rc.stdout.splitlines():
            print(f"VERB        {line}")


if __name__ == "__main__":
    unittest.main()


# The vocabulary as it stood BEFORE this phase, written out as literals. The audit is
# explicit that the foundation is fixed before OKF grows, and a fix that quietly added a
# record type would be an expansion wearing a bug fix's commit message. Compared by
# literal rather than by `len()`: a rename is an expansion too.
RECORD_TYPES_BEFORE_PHASE_6 = ("observation", "claim", "decision", "constraint",
                               "hypothesis", "conclusion")
RELATIONS_BEFORE_PHASE_6 = ("derived_from", "supersedes", "conflicts_with")


@needs_live_corpus
class TheProjectionReadsTheProductionSchema(unittest.TestCase):
    """PHASE 6 (fourth audit). The projection read `e["id"]` and `e["at"]`; production
    emits `target` and `ts`. Every decision record on the real stream therefore read
    `None moved reported -> accepted` — a knowledge record naming no finding, in the one
    layer whose justification is provenance. And 133 of its 266 links pointed at records
    that did not exist, while `verify_bundle` reported the bundle healthy because it
    checked file checksums.

    Everything here runs on THIS REPOSITORY'S real state and event stream."""

    @classmethod
    def setUpClass(cls):
        envelope = xcheck_submodule("envelope")
        cls.state = state_mod.load_state(REPO / "audit")
        cls.events = envelope.read_events(REPO)
        cls.records = okf.project_bundle(cls.state, cls.events)
        cls.ids = {r["id"] for r in cls.records}
        cls.links = [(r["id"], rel, t) for r in cls.records
                     for rel, ts in r["links"].items() for t in ts]

    def test_the_real_stream_carries_target_and_ts_and_not_id_and_at(self):
        rows = [e for e in self.events if e.get("event") == "state_transition"]
        self.assertTrue(rows, "this checkout carries no transition events")
        for projection_name, emitted in okf.EVENT_FIELDS.items():
            have = [e for e in rows if e.get(emitted) is not None]
            fiction = [e for e in rows if e.get(projection_name) is not None]
            print(f"\n  SCHEMA     state_transition.{emitted:<8} on {len(have)} of "
                  f"{len(rows)}; .{projection_name:<3} (what the projection asked for) "
                  f"on {len(fiction)}")
            self.assertTrue(have, f"production does not emit {emitted}")
            self.assertEqual([], fiction,
                             f"an event carries {projection_name!r} — the emitter changed "
                             f"and the adapter has not")

    def test_a_decision_record_names_its_finding(self):
        decisions = [r for r in self.records if r["type"] == okf.DECISION]
        self.assertTrue(decisions, "the real stream produced no decision records")
        for rec in decisions:
            print(f"  DECISION   {rec['text']!r}  freshness={rec['freshness']}")
            self.assertNotIn("None moved", rec["text"],
                             "the decision record still names no finding")
            self.assertIsNotNone(rec["finding"])
            self.assertNotEqual(rec["freshness"], rec["source_revision"])

    def test_the_real_projection_has_no_dangling_links(self):
        dangling = [l for l in self.links if l[2] not in self.ids]
        by_source = {}
        for src, rel, _t in dangling:
            kind = next(r["type"] for r in self.records if r["id"] == src)
            by_source[(kind, rel)] = by_source.get((kind, rel), 0) + 1
        print(f"  LINKS      {len(self.links)} link(s), {len(dangling)} dangling"
              + (f" {by_source}" if dangling else ""))
        self.assertEqual([], dangling, f"{len(dangling)} of {len(self.links)} links "
                                       f"resolve to nothing: {by_source}")
        self.assertGreater(len(self.links), 200,
                           "a projection with almost no links cannot demonstrate that "
                           "its links resolve")

    def test_an_observation_id_is_built_in_exactly_one_place(self):
        """Structural, over the AST. The defect was two constructors that agreed and a
        third that did not, so counting them is the check — a test that only compared
        two ids would pass on any two that happened to match."""
        tree = ast.parse((REPO / "xcheck" / "okf.py").read_text(encoding="utf-8"))
        sites = []
        for node in ast.walk(tree):
            if not (isinstance(node, ast.Call) and isinstance(node.func, ast.Name)
                    and node.func.id == "_rid" and node.args):
                continue
            first = node.args[0]
            if isinstance(first, ast.Name) and first.id == "OBSERVATION":
                sites.append(node.lineno)
        print(f"  ONE ID     `_rid(OBSERVATION, ...)` at line(s) {sites}")
        self.assertEqual(1, len(sites),
                         f"an observation id is built at {len(sites)} places: {sites}")
        enclosing = [n.name for n in ast.walk(tree)
                     if isinstance(n, ast.FunctionDef)
                     and any(getattr(c, "lineno", None) in sites for c in ast.walk(n))]
        self.assertIn("observation_id", enclosing)

    def test_claim_and_hypothesis_both_reach_the_same_observation(self):
        """The two consumers of that one constructor, on real records: every finding's
        observation is pointed at by both its claim and, where a hypothesis covers its
        dimension, by that hypothesis."""
        obs = {r["id"] for r in self.records if r["type"] == okf.OBSERVATION}
        claims = {t for r in self.records if r["type"] == okf.CLAIM
                  for t in r["links"].get(okf.DERIVED_FROM, ())}
        hypos = {t for r in self.records if r["type"] == okf.HYPOTHESIS
                 for t in r["links"].get(okf.DERIVED_FROM, ())}
        print(f"  REACH      {len(obs)} observation(s); claims reach "
              f"{len(claims & obs)}, hypotheses reach {len(hypos & obs)}")
        self.assertEqual(set(), claims - obs)
        self.assertEqual(set(), hypos - obs)
        self.assertTrue(hypos, "no hypothesis linked anything")


@needs_live_corpus
class TheVerifierChecksWhatTheBundleSays(unittest.TestCase):
    """Checksums say the bytes are the bytes somebody wrote. They say nothing about
    whether what was written means anything, and that is how a bundle with 133 dangling
    links verified clean."""

    def setUp(self):
        fx, st, records = built()
        self.fx, self.records = fx, records
        okf.write_bundle(fx.root, records)

    def plant(self, mutate):
        """Rewrite `records.jsonl` and its manifest checksum, so only the SEMANTIC check
        can catch the plant. Leaving the checksum stale would let the old check fire and
        the test would pass for the wrong reason."""
        rows = [dict(r) for r in self.records]
        mutate(rows)
        okf.write_bundle(self.fx.root, rows)
        return okf.verify_bundle(self.fx.root)

    def test_CONTROL_a_correct_bundle_verifies_clean(self):
        self.assertEqual([], okf.verify_bundle(self.fx.root),
                         "the verifier refuses a bundle that is actually correct")
        print(f"\n  CONTROL    {len(self.records)} records verify clean")

    def test_a_dangling_link_is_caught(self):
        def mutate(rows):
            claim = next(r for r in rows if r["type"] == okf.CLAIM)
            claim["links"] = {okf.DERIVED_FROM: ["obse-deadbeef1234"]}
        problems = self.plant(mutate)
        self.assertTrue(any("obse-deadbeef1234" in p and "not a record in this bundle" in p
                            for p in problems), problems)
        self.dangling = problems
        print(f"  DANGLING   {problems[0][:130]}")

    def test_an_unknown_record_type_is_caught(self):
        problems = self.plant(lambda rows: rows[0].update(type="speculation"))
        self.assertTrue(any("unknown record type" in p and "speculation" in p
                            for p in problems), problems)
        print(f"  BAD TYPE   {problems[0][:130]}")

    def test_a_missing_required_field_is_caught(self):
        problems = self.plant(lambda rows: rows[0].pop("locator"))
        self.assertTrue(any("missing required field" in p and "locator" in p
                            for p in problems), problems)
        print(f"  NO FIELD   {problems[0][:130]}")

    def test_the_three_plants_produce_three_DISTINCT_messages(self):
        """N plants can cover fewer than N defects. Asserted on the messages themselves,
        because three arms that all read `the bundle is invalid` would be one check."""
        messages = {}
        for name, mutate in (
                ("dangling", lambda rows: rows[1].update(
                    links={okf.DERIVED_FROM: ["obse-deadbeef1234"]})),
                ("bad-type", lambda rows: rows[0].update(type="speculation")),
                ("no-field", lambda rows: rows[0].pop("locator"))):
            okf.write_bundle(self.fx.root, [dict(r) for r in self.records])
            messages[name] = self.plant(mutate)[0]
        self.assertEqual(3, len({m.split(":", 1)[1].strip()[:40]
                                 for m in messages.values()}),
                         f"the plants share a message: {messages}")
        print("  DISTINCT   " + " | ".join(f"{k}: {v.split(':', 1)[1].strip()[:40]}"
                                           for k, v in sorted(messages.items())))

    def test_a_half_anchored_record_is_refused_and_a_fully_unanchored_one_is_counted(self):
        problems = self.plant(lambda rows: rows[0].update(locator="xcheck/util.py"))
        self.assertTrue(any("half a source anchor" in p for p in problems), problems)
        print(f"  PARTIAL    {problems[0][:140]}")

        okf.write_bundle(self.fx.root, [dict(r) for r in self.records])
        manifest = json.loads(
            (okf.bundle_dir(self.fx.root) / okf.MANIFEST_NAME).read_text(encoding="utf-8"))
        counted = sum(1 for r in self.records if okf.anchor_state(r) == okf.UNANCHORED)
        self.assertEqual(counted, manifest["unanchored"])
        self.assertGreater(counted, 0, "this fixture cannot exercise the count")
        print(f"  UNANCHORED manifest declares {manifest['unanchored']} of "
              f"{len(self.records)}")

    def test_a_manifest_that_hides_the_unanchored_count_is_refused(self):
        path = okf.bundle_dir(self.fx.root) / okf.MANIFEST_NAME
        manifest = json.loads(path.read_text(encoding="utf-8"))
        manifest.pop("unanchored")
        path.write_text(json.dumps(manifest, indent=2, sort_keys=True) + "\n",
                        encoding="utf-8")
        self.assertTrue(any("does not say how many records are unanchored" in p
                            for p in okf.verify_bundle(self.fx.root)))

    def test_the_real_bundle_verifies_clean(self):
        """The control that matters: the projection of this repository's own state and
        events, written and verified end to end."""
        envelope = xcheck_submodule("envelope")
        st = state_mod.load_state(REPO / "audit")
        records = okf.project_bundle(st, envelope.read_events(REPO))
        okf.write_bundle(self.fx.root, records)
        self.assertEqual([], okf.verify_bundle(self.fx.root))
        print(f"  REAL       {len(records)} records from the real audit verify clean")


class TheVocabularyDidNotGrow(unittest.TestCase):
    """The audit forbids expanding OKF before the foundation holds. This phase is a fix,
    and this is what stops it becoming an expansion."""

    def test_the_record_types_are_exactly_what_they_were(self):
        self.assertEqual(RECORD_TYPES_BEFORE_PHASE_6, okf.RECORD_TYPES)

    def test_the_relations_are_exactly_what_they_were(self):
        self.assertEqual(RELATIONS_BEFORE_PHASE_6, okf.RELATIONS)


# ------------------------------------------------------ PHASE 9 (fifth audit)

@needs_live_corpus
class EveryExportedEntityResolvesAgainstOneTable(unittest.TestCase):
    """The audit's finding, on the real corpus: 288 records, 266 links, 0 dangling — and
    13 references in the bundle's PROPOSALS pointing at records nobody exported, with
    `verify_bundle` returning `[]`.

    `classes.proposals_for` minted an OBSERVATION per class member and cited its id.
    Nothing exports those: `write_bundle` writes the projection and the proposals, never
    a third list. Same defect class as the previous run's 133 dangling links, one surface
    over — which is what happens when the referential check lives beside `records.jsonl`
    instead of at the table.
    """

    @classmethod
    def setUpClass(cls):
        envelope = xcheck_submodule("envelope")
        cls.classes = xcheck_submodule("classes")
        cls.state = state_mod.load_state(REPO / "audit")
        cls.records = okf.project_bundle(cls.state, envelope.read_events(REPO))
        found, _ung = cls.classes.candidates(cls.state, REPO)
        cls.found = found
        cls.proposals = cls.classes.proposals_for(found, cls.records)

    def bundle(self, proposals):
        import tempfile
        root = Path(tempfile.mkdtemp(prefix="xcheck-okf9-"))
        self.addCleanup(lambda: __import__("shutil").rmtree(root, ignore_errors=True))
        (root / "audit").mkdir(parents=True)
        okf.write_bundle(root, self.records, proposals=proposals)
        return root

    def refs(self, proposals):
        return [(n, f, t) for n, p in enumerate(proposals, 1)
                for f in okf.PROPOSAL_REFS for t in (p.get(f) or ())]

    def test_every_reference_in_every_exported_entity_resolves(self):
        """Criterion 2, counted by kind so the reader can see what was checked."""
        ids = {r["id"] for r in self.records}
        links = [(r["id"], rel, t) for r in self.records
                 for rel, ts in (r.get("links") or {}).items() for t in ts]
        refs = self.refs(self.proposals)
        print(f"\n  ONE TABLE  {len(ids)} exported record(s)")
        print(f"    records    {len(self.records):>4}   links {len(links)}, "
              f"dangling {len([1 for _i, _r, t in links if t not in ids])}")
        print(f"    proposals  {len(self.proposals):>4}   references {len(refs)}, "
              f"dangling {len([1 for _n, _f, t in refs if t not in ids])}")
        self.assertTrue(refs, "no proposal reference exists — nothing is being checked")
        for _n, field, target in refs:
            self.assertIn(target, ids, f"proposal {field} cites {target}")
        for _i, _rel, target in links:
            self.assertIn(target, ids)
        self.assertEqual([], okf.verify_bundle(self.bundle(self.proposals)))

    def test_a_planted_dangling_proposal_reference_is_caught_by_name(self):
        """Criterion 3. The plant proves the verifier moved: this exact bundle, with this
        exact reference, returned `[]` before the fix."""
        poisoned = [json.loads(json.dumps(p)) for p in self.proposals]
        poisoned[0]["evidence"][0] = "obse-000000000000"
        problems = okf.verify_bundle(self.bundle(poisoned))
        print(f"  PLANTED    {problems[0][:150]}")
        self.assertEqual(1, len(problems))
        self.assertIn("obse-000000000000", problems[0])
        self.assertIn("not a record in this bundle", problems[0])
        self.assertIn("class-candidate", problems[0],
                      "the message does not name the entity carrying the reference")

    def test_CONTROL_the_same_bundle_unpoisoned_verifies_clean(self):
        """Criterion 4. Without this the arm above is satisfied by a verifier that
        refuses everything."""
        problems = okf.verify_bundle(self.bundle(self.proposals))
        print(f"  CONTROL    {len(self.records)} records + {len(self.proposals)} "
              f"proposals ({len(self.refs(self.proposals))} references) -> "
              f"{problems or 'clean'}")
        self.assertEqual([], problems)

    def test_the_proposals_cite_records_rather_than_minting_them(self):
        """The fix the phase asked for, asserted at the source: inventing a record to
        satisfy a reference is how the 133 dangling links happened."""
        by_finding = {r.get("finding"): r["id"] for r in self.records
                      if r.get("type") == okf.OBSERVATION and r.get("finding")}
        for cand, prop in zip(self.found, self.proposals):
            cited = set(prop["evidence"])
            self.assertEqual({by_finding[m] for m in cand["members"] if m in by_finding},
                             cited, "a proposal cites something other than the "
                                    "observation this bundle already exports")
        src = Path(xcheck_submodule("classes").__file__).read_text(encoding="utf-8")
        fn = src[src.index("def proposals_for("):src.index("MAX_INLINE_LINES")]
        self.assertNotIn("knowledge_record", fn,
                         "the proposal builder still mints records")
        print(f"  CITES      {len(self.proposals)} proposal(s) cite "
              f"{sum(len(p['evidence']) for p in self.proposals)} EXISTING observation(s)")

    def test_ONE_implementation_checks_both_kinds(self):
        """Criterion 5. Two checkers over two entity kinds is how the second surface got
        missed the first time; asserted structurally rather than by reading."""
        src = Path(xcheck_submodule("okf").__file__).read_text(encoding="utf-8")
        tree = ast.parse(src)
        fns = {n.name: n for n in tree.body if isinstance(n, ast.FunctionDef)}
        # The literal as it appears in SOURCE: both messages are f-strings split across
        # lines, so the runtime sentence exists nowhere as one token.
        needle = "record in this bundle"
        carriers = sorted(name for name, node in fns.items()
                          if needle in ast.get_source_segment(src, node))
        self.assertEqual(["bundle_problems"], carriers,
                         f"the referential check exists in more than one function: "
                         f"{carriers}")
        # ...and the one function builds its table ONCE, from the records.
        body = ast.get_source_segment(src, fns["bundle_problems"])
        self.assertEqual(1, body.count("ids = {"),
                         "the checker builds a second id table")
        self.assertEqual(1, len([n for n in ast.walk(tree)
                                 if isinstance(n, ast.Call)
                                 and getattr(n.func, "id", "") == "bundle_problems"]),
                         "bundle_problems has more than one caller inside okf.py")
        print(f"  STRUCTURAL the referential check lives in {carriers[0]} only, over one "
              f"table, with one caller")

    def test_the_manifest_still_covers_every_member(self):
        """Criterion 8. Proposals were already a manifest member; this asserts it rather
        than assuming, and that the checksum is over what is on disk."""
        import hashlib
        root = self.bundle(self.proposals)
        manifest = json.loads(
            (okf.bundle_dir(root) / okf.MANIFEST_NAME).read_text(encoding="utf-8"))
        members = {p.name for p in okf.bundle_dir(root).iterdir()
                   if p.name != okf.MANIFEST_NAME}
        self.assertEqual(members, set(manifest["files"]),
                         "a bundle member is not named in the manifest")
        for name, meta in sorted(manifest["files"].items()):
            got = hashlib.sha256((okf.bundle_dir(root) / name).read_bytes()).hexdigest()
            self.assertEqual(meta["sha256"], got, name)
            print(f"  MANIFEST   {name:<16} rows={meta['rows']:<4} "
                  f"sha256={meta['sha256'][:12]}…")

    def test_okf_is_still_proposal_only_and_an_input_to_nothing(self):
        """Criterion 7, re-asserted because this phase changed what a proposal carries."""
        for p in self.proposals:
            self.assertEqual("proposed", p["status"])
            self.assertIn("changes nothing", p["note"])
            self.assertTrue(p["verb"].startswith("xcheck "))
        with self.assertRaises(Exception):
            okf.apply_effect(next(iter(okf.FORBIDDEN)))
        cli_src = (REPO / "xcheck" / "cli.py").read_text(encoding="utf-8")
        gate = cli_src[cli_src.index("def cmd_okf("):]
        gate = gate[:gate.index("def cmd_evidence_bundle(")]
        for writer in ("set_status", "write_state", "record_fix", "_apply("):
            self.assertNotIn(writer, gate, f"cmd_okf reaches {writer}")
        print("  PROPOSAL   4 proposals, status='proposed', each naming a verb a human "
              "runs; cmd_okf reaches no write path")


# -------------------------------------------------------------- PHASE 8 (sixth audit)
#
# The fifth audit's dangling references are genuinely fixed. The sixth found two NEW
# false successes in the same verifier, and a third defect behind them:
#
#   1. `{"files": {}, "unanchored": 0}` with BOTH JSONL files absent verified clean — the
#      loop was over the manifest's own file list, so a manifest naming nothing described
#      a complete bundle containing nothing.
#   2. A second record carrying an existing id verified clean — the id table was a SET,
#      and a set is where duplicates go to disappear.
#   3. A read failure became `[]`. An empty bundle has no dangling links, no unknown
#      types and no duplicate ids, so every content check passed over an unreadable file.

class AManifestIsNotTheAuthorityOnWhatABundleIs(unittest.TestCase):
    """FALSE SUCCESS 1, and the declaration that refuses it."""

    def setUp(self):
        self.fx = Fixture(state_doc(findings=FINDINGS,
                                    queue=[queue_pass("P-01", done=True)]))
        self.addCleanup(self.fx.cleanup)

    def empty_manifest(self):
        out = okf.bundle_dir(self.fx.root)
        out.mkdir(parents=True, exist_ok=True)
        for name in okf.BUNDLE_FILES:
            if (out / name).exists():
                (out / name).unlink()
        (out / okf.MANIFEST_NAME).write_text(
            json.dumps({"files": {}, "unanchored": 0}) + "\n", encoding="utf-8")
        return out

    def test_a_manifest_naming_no_files_is_an_incomplete_bundle(self):
        out = self.empty_manifest()
        present = [n for n in okf.BUNDLE_FILES if (out / n).exists()]
        problems = okf.verify_bundle(self.fx.root)
        print("\n  BEFORE     {'files': {}, 'unanchored': 0} with 0 JSONL files "
              "-> verify_bundle returned []")
        print(f"  AFTER      {len(problems)} problem(s); files present on disk: {present}")
        for p in problems:
            print(f"    {p[:104]}")
        self.assertTrue(problems, "an empty manifest still describes a complete bundle")
        joined = " ".join(problems)
        self.assertIn("INCOMPLETE", joined)
        for name in okf.BUNDLE_FILES:
            self.assertIn(name, joined, f"{name} was required but not named in the refusal")

    def test_the_required_set_comes_from_the_EXPORTER_not_a_hand_list(self):
        """Criterion 4. `BUNDLE_FILES` is derived from `bundle_members`, the same function
        `write_bundle` iterates — so a new exported entity type is required in the same
        edit that exports it. Asserted by RUNNING the exporter and reading the directory,
        not by comparing two literals."""
        fx, _st, records = built()
        self.addCleanup(fx.cleanup)
        okf.write_bundle(fx.root, records, proposals=[])
        out = okf.bundle_dir(fx.root)
        written = {p.name for p in out.iterdir()} - {okf.MANIFEST_NAME}
        print(f"  DERIVED    exporter wrote {sorted(written)} · "
              f"BUNDLE_FILES = {list(okf.BUNDLE_FILES)}")
        self.assertEqual(sorted(written), sorted(okf.BUNDLE_FILES),
                         "the exporter writes a file the verifier does not require, or "
                         "requires one it does not write")
        self.assertEqual(tuple(okf.bundle_members()), okf.BUNDLE_FILES)

    def test_a_member_the_exporter_does_not_produce_is_named_unclassified(self):
        """A neighbour added to the manifest by some other hand is reported, not ignored:
        an unclassified member is a file no verifier reads."""
        fx, _st, records = built()
        self.addCleanup(fx.cleanup)
        okf.write_bundle(fx.root, records)
        out = okf.bundle_dir(fx.root)
        manifest = json.loads((out / okf.MANIFEST_NAME).read_text(encoding="utf-8"))
        body = "{}\n"
        (out / "neighbours.jsonl").write_text(body, encoding="utf-8")
        manifest["files"]["neighbours.jsonl"] = {
            "sha256": hashlib.sha256(body.encode()).hexdigest(), "rows": 1,
            "bytes": len(body)}
        (out / okf.MANIFEST_NAME).write_text(json.dumps(manifest, indent=2) + "\n",
                                             encoding="utf-8")
        problems = okf.verify_bundle(fx.root)
        print(f"  UNKNOWN    {problems[0][:104]}")
        self.assertTrue(any("neighbours.jsonl" in p and "unclassified" in p
                            for p in problems),
                        "a member nobody declared was silently accepted")


class ASetIsWhereDuplicatesDisappear(unittest.TestCase):
    """FALSE SUCCESS 2."""

    def setUp(self):
        self.fx, _st, self.records = built()
        self.addCleanup(self.fx.cleanup)

    def test_a_duplicate_id_is_reported_with_both_occurrences(self):
        rows = [dict(r) for r in self.records]
        twice = dict(rows[0])
        rows.insert(1, twice)                      # lines 1 and 2 share an id
        okf.write_bundle(self.fx.root, rows)
        problems = okf.verify_bundle(self.fx.root)
        print(f"\n  BEFORE     {len(rows)} rows, {len({r['id'] for r in rows})} distinct "
              f"ids -> verify_bundle returned []")
        print(f"  AFTER      {problems[0][:118]}")
        self.assertTrue(problems, "two records sharing an id verified clean")
        self.assertIn(twice["id"], problems[0])
        self.assertIn("line 1", problems[0])
        self.assertIn("line 2", problems[0], "only one occurrence was named")

    def test_the_counting_structure_can_SEE_a_duplicate(self):
        """Criterion 2 names it. A set answers "is this id present" identically for one
        copy and for two, so no assertion over a set could ever have caught this."""
        ids = [r["id"] for r in self.records] * 2
        self.assertEqual(len(self.records), len(set(ids)),
                         "a set cannot distinguish 2N records from N")
        at = {}
        for n, rid in enumerate(ids, 1):
            at.setdefault(rid, []).append(n)
        print(f"  STRUCTURE  set(ids) -> {len(set(ids))} id(s) · "
              f"dict of positions -> {sum(len(v) for v in at.values())} occurrence(s) "
              f"over {len(at)} id(s)")
        self.assertEqual(len(ids), sum(len(v) for v in at.values()))
        # Named in the shipped code: the id table maps to a LIST of line numbers, so a
        # second occurrence has somewhere to go. `okf.py` deliberately imports nothing
        # for this — `TheBundleIsDerived` pins the module's dependency set, and growing
        # it to count duplicates would trade one gate for another.
        source = (REPO / "xcheck" / "okf.py").read_text(encoding="utf-8")
        body = source[source.index("def bundle_problems("):]
        body = body[:body.index("\ndef ")]
        self.assertIn("at.setdefault(rec.get(\"id\"), []).append(n)", body,
                      "the duplicate check is not over a structure that keeps occurrences")
        self.assertNotIn("ids = {r.get(\"id\") for r in records}", body,
                         "the set comprehension that could not see a duplicate is back")

    def test_CONTROL_distinct_ids_still_verify_clean(self):
        okf.write_bundle(self.fx.root, self.records)
        self.assertEqual([], okf.verify_bundle(self.fx.root))
        print(f"  CONTROL    {len(self.records)} distinct ids verify clean")


class AbsentDirectoryAndUnreadableAreThreeAnswers(unittest.TestCase):
    """Criterion 3. As they now are for the journal — `ledger.status` learned the same
    lesson two audits ago, and this reader had not."""

    def setUp(self):
        self.fx, _st, self.records = built()
        self.addCleanup(self.fx.cleanup)

    def bundle(self):
        """A FRESH bundle each time. The previous arm may have left a directory standing
        where `records.jsonl` belongs, and write_bundle cannot write through one."""
        import shutil
        out = okf.bundle_dir(self.fx.root)
        if out.exists():
            shutil.rmtree(out)
        okf.write_bundle(self.fx.root, self.records)
        return out / "records.jsonl"

    def test_the_three_are_distinguished_and_none_is_an_empty_list(self):
        answers = {}
        for label, prepare in (
                ("absent", lambda p: p.unlink()),
                ("directory", lambda p: (p.unlink(), p.mkdir())),
                ("unreadable", lambda p: p.chmod(0o000))):
            path = self.bundle()
            prepare(path)
            try:
                answers[label] = okf.verify_bundle(self.fx.root)
            finally:
                if label == "unreadable":
                    path.chmod(0o644)
        print()
        for label, problems in answers.items():
            print(f"  {label:<11} {problems[0][:96]}")
            self.assertTrue(problems, f"{label} produced no problem at all")
        self.assertIn(okf.ABSENT, answers["absent"][0])
        self.assertIn(okf.IS_A_DIRECTORY, answers["directory"][0])
        self.assertIn(okf.UNREADABLE, answers["unreadable"][0])
        texts = [v[0] for v in answers.values()]
        self.assertEqual(3, len(set(texts)), f"three failures, {len(set(texts))} answer(s)")

    def test_read_rows_never_returns_no_rows_and_no_problem_for_a_bad_file(self):
        """The seam itself: `([], None)` is a legitimate answer for an EMPTY file and a
        lie for every other failure, and the two are indistinguishable downstream."""
        out = okf.bundle_dir(self.fx.root)
        out.mkdir(parents=True, exist_ok=True)
        empty = out / "empty.jsonl"
        empty.write_text("", encoding="utf-8")
        rows, problem = okf.read_rows(empty)
        print(f"  EMPTY FILE read_rows -> rows={rows} problem={problem!r}")
        self.assertEqual(([], None), (rows, problem), "an empty file is not a failure")

        gone = out / "not-there.jsonl"
        rows, problem = okf.read_rows(gone)
        print(f"  ABSENT     read_rows -> rows={rows} problem={problem[:60]}…")
        self.assertIsNotNone(problem, "an absent file answered like an empty one")

    def test_malformed_json_is_its_own_answer(self):
        path = self.bundle()
        path.write_text(path.read_text(encoding="utf-8") + "{not json}\n",
                        encoding="utf-8")
        # The checksum now disagrees, which is a DIFFERENT true problem — rewrite the
        # manifest so only the parse can fire, or this passes for the wrong reason.
        out = okf.bundle_dir(self.fx.root)
        manifest = json.loads((out / okf.MANIFEST_NAME).read_text(encoding="utf-8"))
        manifest["files"]["records.jsonl"]["sha256"] = hashlib.sha256(
            path.read_bytes()).hexdigest()
        (out / okf.MANIFEST_NAME).write_text(json.dumps(manifest, indent=2) + "\n",
                                             encoding="utf-8")
        problems = okf.verify_bundle(self.fx.root)
        print(f"  MALFORMED  {problems[0][:96]}")
        self.assertIn(okf.MALFORMED, problems[0])


class OneRouteToAVerdict(unittest.TestCase):
    """Criterion 6: the fix is at the table, and there is no second, laxer path."""

    SOURCE = (REPO / "xcheck" / "okf.py").read_text(encoding="utf-8")

    def function(self, name):
        body = self.SOURCE[self.SOURCE.index(f"def {name}("):]
        end = body.index("\ndef ", 1)
        return body[:end]

    def test_verify_bundle_asks_bundle_completeness_and_nothing_else(self):
        body = self.function("verify_bundle")
        self.assertIn("bundle_completeness(out, manifest)", body)
        # The old loop is gone: no second place decides what files a bundle has.
        self.assertNotIn('manifest.get("files", {})', body,
                         "verify_bundle still consults the manifest as the authority")
        print("\n  ONE ROUTE  verify_bundle -> bundle_completeness, and no `files` "
              "loop of its own")

    #: Every function allowed to open a bundle file itself, and why. A reader outside
    #: this set is a second opinion about what a failure looks like — which is how a
    #: swallowed OSError became `[]` and `[]` became a verdict.
    MAY_OPEN = {
        "read_rows": "the seam itself: it is what turns a failure into a named problem",
        "verify_bundle": "reads the MANIFEST, which must be read before any member is",
        "bundle_completeness": "hashes BYTES — a checksum is not a parse and fails on "
                               "its own terms",
    }

    def test_every_reader_of_a_bundle_file_goes_through_read_rows(self):
        tree = ast.parse(self.SOURCE)
        owner = {}
        for node in ast.walk(tree):
            if isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef)):
                for child in ast.walk(node):
                    owner[id(child)] = node.name
        stray = []
        seen = collections.defaultdict(list)
        for node in ast.walk(tree):
            if (isinstance(node, ast.Call) and isinstance(node.func, ast.Attribute)
                    and node.func.attr in ("read_text", "read_bytes")):
                who = owner.get(id(node), "<module>")
                seen[who].append(node.lineno)
                if who not in self.MAY_OPEN:
                    stray.append((who, node.lineno, node.func.attr))
        print(f"  READERS    {dict(seen)}")
        self.assertEqual([], stray,
                         f"function(s) read a bundle file outside the declared set "
                         f"{sorted(self.MAY_OPEN)}: {stray}")
        # And the declaration is not stale: every name in it still exists and still reads.
        self.assertEqual(sorted(self.MAY_OPEN), sorted(seen),
                         "a declared reader no longer reads, or a new one appeared")

    def test_a_verdict_that_cannot_be_computed_is_not_a_pass(self):
        """Criterion 7, through the CLI's own exit code."""
        fx, _st, records = built()
        self.addCleanup(fx.cleanup)
        okf.write_bundle(fx.root, records)
        (okf.bundle_dir(fx.root) / okf.MANIFEST_NAME).write_text("{not json",
                                                                 encoding="utf-8")
        problems = okf.verify_bundle(fx.root)
        print(f"  NO VERDICT {problems[0][:96]}")
        self.assertTrue(problems)
        self.assertIn("not a pass", problems[0])
        cli_src = (REPO / "xcheck" / "cli.py").read_text(encoding="utf-8")
        gate = cli_src[cli_src.index("def cmd_okf("):]
        gate = gate[:gate.index("def cmd_evidence_bundle(")]
        self.assertIn("return 1 if problems else 0", gate)


@needs_live_corpus
class TheRealBundleStillVerifiesClean(unittest.TestCase):
    """Criterion 5. The project's own corpus, exported through the real entry point.

    Written to a TEMP root rather than `audit/okf/`: the operator's scope excludes
    `audit/` from being edited, and a control that had to modify the subject to run would
    be measuring a tree this run had changed.
    """

    @classmethod
    def setUpClass(cls):
        import shutil, tempfile
        from xcheck.envelope import read_events
        classes_mod = xcheck_submodule("classes")
        st = state_mod.load_state(REPO / "audit")
        cls.records = okf.project_bundle(st, read_events(REPO))
        found, _ungrouped = classes_mod.candidates(st, REPO)
        cls.proposals = classes_mod.proposals_for(found, cls.records) if found else []
        cls.tmp = Path(tempfile.mkdtemp(prefix="okf-control-"))
        (cls.tmp / "audit").mkdir(parents=True)
        cls.manifest = okf.write_bundle(cls.tmp, cls.records, proposals=cls.proposals)
        cls.addClassCleanup(shutil.rmtree, cls.tmp, ignore_errors=True)

    def test_it_verifies_clean_with_its_counts_printed(self):
        refs = sum(len(p.get(f) or ()) for p in self.proposals
                   for f in okf.PROPOSAL_REFS)
        links = sum(len(t) for r in self.records
                    for t in (r.get("links") or {}).values())
        problems = okf.verify_bundle(self.tmp)
        print(f"\n  REAL       {len(self.records)} record(s), {links} link(s), "
              f"{len(self.proposals)} proposal(s), {refs} evidence reference(s)")
        print(f"  REAL       manifest files {sorted(self.manifest['files'])} · "
              f"verify_bundle -> {problems}")
        self.assertEqual([], problems, "the real bundle no longer verifies")
        self.assertEqual(288, len(self.records))
        self.assertEqual(266, links)
        self.assertEqual(13, refs)

    def test_the_real_bundle_has_no_duplicate_ids(self):
        ids = [r["id"] for r in self.records]
        counted = collections.Counter(ids)
        worst = counted.most_common(1)[0]
        print(f"  REAL       {len(ids)} record(s), {len(counted)} distinct id(s); "
              f"most repeated: {worst[0]} x{worst[1]}")
        self.assertEqual(len(ids), len(counted))
